// <auto-generated />
using System;
using FitnessCheck.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessCheck.Migrations
{
    [DbContext(typeof(FitnessCheckDbContext))]
    partial class FitnessCheckDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FitnessCheck.Data.Entities.Cohort", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Baccalaureate")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ClassNameBaccalaureate")
                        .HasColumnType("longtext");

                    b.Property<string>("ClassNameVocationalEducation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<uint>("FirstSchoolYear")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("SchoolYear")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.ToTable("Cohorts");
                });

            modelBuilder.Entity("FitnessCheck.Data.Entities.CoreStrengthAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<byte>("AttemptNumber")
                        .HasColumnType("tinyint unsigned");

                    b.Property<Guid>("CohortId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime>("MomentUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<uint>("Points")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("ResultInSeconds")
                        .HasColumnType("int unsigned");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CohortId");

                    b.ToTable("CoreStrengthAttempts");
                });

            modelBuilder.Entity("FitnessCheck.Data.Entities.MedicineBallPushAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<byte>("AttemptNumber")
                        .HasColumnType("tinyint unsigned");

                    b.Property<Guid>("CohortId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime>("MomentUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<uint>("Points")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("ResultInCentimeters")
                        .HasColumnType("int unsigned");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CohortId");

                    b.ToTable("MedicineBallPushAttempts");
                });

            modelBuilder.Entity("FitnessCheck.Data.Entities.OneLegStandAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<byte>("AttemptNumber")
                        .HasColumnType("tinyint unsigned");

                    b.Property<Guid>("CohortId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Foot")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime>("MomentUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<uint>("Points")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("ResultInSeconds")
                        .HasColumnType("int unsigned");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CohortId");

                    b.ToTable("OneLegStandAttempts");
                });

            modelBuilder.Entity("FitnessCheck.Data.Entities.ShuttleRunAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<byte>("AttemptNumber")
                        .HasColumnType("tinyint unsigned");

                    b.Property<Guid>("CohortId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime>("MomentUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<uint>("Points")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("ResultInMilliseconds")
                        .HasColumnType("int unsigned");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CohortId");

                    b.ToTable("ShuttleRunAttempts");
                });

            modelBuilder.Entity("FitnessCheck.Data.Entities.StandingLongJumpAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<byte>("AttemptNumber")
                        .HasColumnType("tinyint unsigned");

                    b.Property<Guid>("CohortId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime>("MomentUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<uint>("Points")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("ResultInCentimeters")
                        .HasColumnType("int unsigned");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CohortId");

                    b.ToTable("StandingLongJumpAttempts");
                });

            modelBuilder.Entity("FitnessCheck.Data.Entities.TwelveMinutesRunAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<byte>("AttemptNumber")
                        .HasColumnType("tinyint unsigned");

                    b.Property<Guid>("CohortId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime>("MomentUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<uint>("Points")
                        .HasColumnType("int unsigned");

                    b.Property<float>("ResultInRounds")
                        .HasColumnType("float");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CohortId");

                    b.ToTable("TwelveMinutesRunAttempts");
                });

            modelBuilder.Entity("FitnessCheckModels.ResultsCalculation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CoreStrength")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MedicineBallPush")
                        .HasColumnType("int");

                    b.Property<int>("OneLegStand")
                        .HasColumnType("int");

                    b.Property<uint>("Points")
                        .HasColumnType("int unsigned");

                    b.Property<int>("ShuttleRun")
                        .HasColumnType("int");

                    b.Property<int>("StandingLongJump")
                        .HasColumnType("int");

                    b.Property<float>("TwelveMinutesRun")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("Results");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CoreStrength = 0,
                            Gender = "m",
                            Grade = "TE",
                            MedicineBallPush = 0,
                            OneLegStand = 0,
                            Points = 0u,
                            ShuttleRun = 100000,
                            StandingLongJump = 0,
                            TwelveMinutesRun = 0f
                        },
                        new
                        {
                            ID = 2,
                            CoreStrength = 5,
                            Gender = "m",
                            Grade = "TE",
                            MedicineBallPush = 410,
                            OneLegStand = 11,
                            Points = 1u,
                            ShuttleRun = 12260,
                            StandingLongJump = 165,
                            TwelveMinutesRun = 31f
                        },
                        new
                        {
                            ID = 3,
                            CoreStrength = 10,
                            Gender = "m",
                            Grade = "TE",
                            MedicineBallPush = 420,
                            OneLegStand = 14,
                            Points = 2u,
                            ShuttleRun = 12120,
                            StandingLongJump = 170,
                            TwelveMinutesRun = 31.5f
                        },
                        new
                        {
                            ID = 4,
                            CoreStrength = 15,
                            Gender = "m",
                            Grade = "TE",
                            MedicineBallPush = 430,
                            OneLegStand = 17,
                            Points = 3u,
                            ShuttleRun = 11980,
                            StandingLongJump = 175,
                            TwelveMinutesRun = 32f
                        },
                        new
                        {
                            ID = 5,
                            CoreStrength = 20,
                            Gender = "m",
                            Grade = "TE",
                            MedicineBallPush = 440,
                            OneLegStand = 20,
                            Points = 4u,
                            ShuttleRun = 11840,
                            StandingLongJump = 180,
                            TwelveMinutesRun = 32.5f
                        },
                        new
                        {
                            ID = 6,
                            CoreStrength = 25,
                            Gender = "m",
                            Grade = "TE",
                            MedicineBallPush = 450,
                            OneLegStand = 23,
                            Points = 5u,
                            ShuttleRun = 11700,
                            StandingLongJump = 185,
                            TwelveMinutesRun = 33f
                        },
                        new
                        {
                            ID = 7,
                            CoreStrength = 30,
                            Gender = "m",
                            Grade = "TE",
                            MedicineBallPush = 470,
                            OneLegStand = 26,
                            Points = 6u,
                            ShuttleRun = 11560,
                            StandingLongJump = 190,
                            TwelveMinutesRun = 33.5f
                        },
                        new
                        {
                            ID = 8,
                            CoreStrength = 40,
                            Gender = "m",
                            Grade = "EE",
                            MedicineBallPush = 490,
                            OneLegStand = 29,
                            Points = 7u,
                            ShuttleRun = 11420,
                            StandingLongJump = 195,
                            TwelveMinutesRun = 34.5f
                        },
                        new
                        {
                            ID = 9,
                            CoreStrength = 50,
                            Gender = "m",
                            Grade = "EE",
                            MedicineBallPush = 510,
                            OneLegStand = 31,
                            Points = 8u,
                            ShuttleRun = 11280,
                            StandingLongJump = 200,
                            TwelveMinutesRun = 35f
                        },
                        new
                        {
                            ID = 10,
                            CoreStrength = 60,
                            Gender = "m",
                            Grade = "EE",
                            MedicineBallPush = 530,
                            OneLegStand = 33,
                            Points = 9u,
                            ShuttleRun = 11140,
                            StandingLongJump = 205,
                            TwelveMinutesRun = 35.5f
                        },
                        new
                        {
                            ID = 11,
                            CoreStrength = 70,
                            Gender = "m",
                            Grade = "EE",
                            MedicineBallPush = 550,
                            OneLegStand = 35,
                            Points = 10u,
                            ShuttleRun = 11000,
                            StandingLongJump = 210,
                            TwelveMinutesRun = 36f
                        },
                        new
                        {
                            ID = 12,
                            CoreStrength = 80,
                            Gender = "m",
                            Grade = "EE",
                            MedicineBallPush = 570,
                            OneLegStand = 37,
                            Points = 11u,
                            ShuttleRun = 10860,
                            StandingLongJump = 215,
                            TwelveMinutesRun = 36.5f
                        },
                        new
                        {
                            ID = 13,
                            CoreStrength = 90,
                            Gender = "m",
                            Grade = "EE",
                            MedicineBallPush = 590,
                            OneLegStand = 39,
                            Points = 12u,
                            ShuttleRun = 10720,
                            StandingLongJump = 220,
                            TwelveMinutesRun = 37.5f
                        },
                        new
                        {
                            ID = 14,
                            CoreStrength = 100,
                            Gender = "m",
                            Grade = "EE",
                            MedicineBallPush = 610,
                            OneLegStand = 41,
                            Points = 13u,
                            ShuttleRun = 10580,
                            StandingLongJump = 225,
                            TwelveMinutesRun = 38f
                        },
                        new
                        {
                            ID = 15,
                            CoreStrength = 110,
                            Gender = "m",
                            Grade = "EE",
                            MedicineBallPush = 630,
                            OneLegStand = 43,
                            Points = 14u,
                            ShuttleRun = 10440,
                            StandingLongJump = 230,
                            TwelveMinutesRun = 38.5f
                        },
                        new
                        {
                            ID = 16,
                            CoreStrength = 120,
                            Gender = "m",
                            Grade = "EE",
                            MedicineBallPush = 650,
                            OneLegStand = 45,
                            Points = 15u,
                            ShuttleRun = 10300,
                            StandingLongJump = 235,
                            TwelveMinutesRun = 39f
                        },
                        new
                        {
                            ID = 17,
                            CoreStrength = 130,
                            Gender = "m",
                            Grade = "UEE",
                            MedicineBallPush = 670,
                            OneLegStand = 47,
                            Points = 16u,
                            ShuttleRun = 10160,
                            StandingLongJump = 240,
                            TwelveMinutesRun = 39.5f
                        },
                        new
                        {
                            ID = 18,
                            CoreStrength = 145,
                            Gender = "m",
                            Grade = "UEE",
                            MedicineBallPush = 690,
                            OneLegStand = 49,
                            Points = 17u,
                            ShuttleRun = 10020,
                            StandingLongJump = 245,
                            TwelveMinutesRun = 40.5f
                        },
                        new
                        {
                            ID = 19,
                            CoreStrength = 160,
                            Gender = "m",
                            Grade = "UEE",
                            MedicineBallPush = 710,
                            OneLegStand = 51,
                            Points = 18u,
                            ShuttleRun = 9880,
                            StandingLongJump = 250,
                            TwelveMinutesRun = 41f
                        },
                        new
                        {
                            ID = 20,
                            CoreStrength = 175,
                            Gender = "m",
                            Grade = "UEE",
                            MedicineBallPush = 730,
                            OneLegStand = 54,
                            Points = 19u,
                            ShuttleRun = 9740,
                            StandingLongJump = 255,
                            TwelveMinutesRun = 41.5f
                        },
                        new
                        {
                            ID = 21,
                            CoreStrength = 190,
                            Gender = "m",
                            Grade = "UEE",
                            MedicineBallPush = 750,
                            OneLegStand = 58,
                            Points = 20u,
                            ShuttleRun = 9600,
                            StandingLongJump = 260,
                            TwelveMinutesRun = 42f
                        },
                        new
                        {
                            ID = 22,
                            CoreStrength = 210,
                            Gender = "m",
                            Grade = "UEE",
                            MedicineBallPush = 770,
                            OneLegStand = 64,
                            Points = 21u,
                            ShuttleRun = 9460,
                            StandingLongJump = 265,
                            TwelveMinutesRun = 42.5f
                        },
                        new
                        {
                            ID = 23,
                            CoreStrength = 230,
                            Gender = "m",
                            Grade = "UED",
                            MedicineBallPush = 790,
                            OneLegStand = 71,
                            Points = 22u,
                            ShuttleRun = 9320,
                            StandingLongJump = 270,
                            TwelveMinutesRun = 43.5f
                        },
                        new
                        {
                            ID = 24,
                            CoreStrength = 250,
                            Gender = "m",
                            Grade = "UED",
                            MedicineBallPush = 810,
                            OneLegStand = 79,
                            Points = 23u,
                            ShuttleRun = 9180,
                            StandingLongJump = 275,
                            TwelveMinutesRun = 44f
                        },
                        new
                        {
                            ID = 25,
                            CoreStrength = 270,
                            Gender = "m",
                            Grade = "UED",
                            MedicineBallPush = 830,
                            OneLegStand = 88,
                            Points = 24u,
                            ShuttleRun = 9040,
                            StandingLongJump = 280,
                            TwelveMinutesRun = 44.5f
                        },
                        new
                        {
                            ID = 26,
                            CoreStrength = 290,
                            Gender = "m",
                            Grade = "UED",
                            MedicineBallPush = 850,
                            OneLegStand = 100,
                            Points = 25u,
                            ShuttleRun = 8900,
                            StandingLongJump = 285,
                            TwelveMinutesRun = 45f
                        },
                        new
                        {
                            ID = 27,
                            CoreStrength = 0,
                            Gender = "f",
                            Grade = "TE",
                            MedicineBallPush = 0,
                            OneLegStand = 0,
                            Points = 0u,
                            ShuttleRun = 100000,
                            StandingLongJump = 0,
                            TwelveMinutesRun = 0f
                        },
                        new
                        {
                            ID = 28,
                            CoreStrength = 5,
                            Gender = "f",
                            Grade = "TE",
                            MedicineBallPush = 316,
                            OneLegStand = 11,
                            Points = 1u,
                            ShuttleRun = 13000,
                            StandingLongJump = 116,
                            TwelveMinutesRun = 24f
                        },
                        new
                        {
                            ID = 29,
                            CoreStrength = 9,
                            Gender = "f",
                            Grade = "TE",
                            MedicineBallPush = 321,
                            OneLegStand = 14,
                            Points = 2u,
                            ShuttleRun = 12950,
                            StandingLongJump = 119,
                            TwelveMinutesRun = 24.5f
                        },
                        new
                        {
                            ID = 30,
                            CoreStrength = 14,
                            Gender = "f",
                            Grade = "TE",
                            MedicineBallPush = 327,
                            OneLegStand = 17,
                            Points = 3u,
                            ShuttleRun = 12820,
                            StandingLongJump = 123,
                            TwelveMinutesRun = 25f
                        },
                        new
                        {
                            ID = 31,
                            CoreStrength = 18,
                            Gender = "f",
                            Grade = "TE",
                            MedicineBallPush = 332,
                            OneLegStand = 20,
                            Points = 4u,
                            ShuttleRun = 12680,
                            StandingLongJump = 126,
                            TwelveMinutesRun = 26f
                        },
                        new
                        {
                            ID = 32,
                            CoreStrength = 23,
                            Gender = "f",
                            Grade = "TE",
                            MedicineBallPush = 338,
                            OneLegStand = 23,
                            Points = 5u,
                            ShuttleRun = 12540,
                            StandingLongJump = 130,
                            TwelveMinutesRun = 26.5f
                        },
                        new
                        {
                            ID = 33,
                            CoreStrength = 27,
                            Gender = "f",
                            Grade = "TE",
                            MedicineBallPush = 349,
                            OneLegStand = 26,
                            Points = 6u,
                            ShuttleRun = 12400,
                            StandingLongJump = 133,
                            TwelveMinutesRun = 27f
                        },
                        new
                        {
                            ID = 34,
                            CoreStrength = 36,
                            Gender = "f",
                            Grade = "EE",
                            MedicineBallPush = 360,
                            OneLegStand = 29,
                            Points = 7u,
                            ShuttleRun = 12270,
                            StandingLongJump = 137,
                            TwelveMinutesRun = 28f
                        },
                        new
                        {
                            ID = 35,
                            CoreStrength = 45,
                            Gender = "f",
                            Grade = "EE",
                            MedicineBallPush = 371,
                            OneLegStand = 31,
                            Points = 8u,
                            ShuttleRun = 12130,
                            StandingLongJump = 140,
                            TwelveMinutesRun = 28.5f
                        },
                        new
                        {
                            ID = 36,
                            CoreStrength = 54,
                            Gender = "f",
                            Grade = "EE",
                            MedicineBallPush = 382,
                            OneLegStand = 33,
                            Points = 9u,
                            ShuttleRun = 11990,
                            StandingLongJump = 144,
                            TwelveMinutesRun = 29f
                        },
                        new
                        {
                            ID = 37,
                            CoreStrength = 63,
                            Gender = "f",
                            Grade = "EE",
                            MedicineBallPush = 393,
                            OneLegStand = 35,
                            Points = 10u,
                            ShuttleRun = 11860,
                            StandingLongJump = 147,
                            TwelveMinutesRun = 30f
                        },
                        new
                        {
                            ID = 38,
                            CoreStrength = 72,
                            Gender = "f",
                            Grade = "EE",
                            MedicineBallPush = 404,
                            OneLegStand = 37,
                            Points = 11u,
                            ShuttleRun = 11720,
                            StandingLongJump = 151,
                            TwelveMinutesRun = 30.5f
                        },
                        new
                        {
                            ID = 39,
                            CoreStrength = 81,
                            Gender = "f",
                            Grade = "EE",
                            MedicineBallPush = 415,
                            OneLegStand = 39,
                            Points = 12u,
                            ShuttleRun = 11580,
                            StandingLongJump = 154,
                            TwelveMinutesRun = 31f
                        },
                        new
                        {
                            ID = 40,
                            CoreStrength = 90,
                            Gender = "f",
                            Grade = "EE",
                            MedicineBallPush = 426,
                            OneLegStand = 41,
                            Points = 13u,
                            ShuttleRun = 11440,
                            StandingLongJump = 158,
                            TwelveMinutesRun = 32f
                        },
                        new
                        {
                            ID = 41,
                            CoreStrength = 99,
                            Gender = "f",
                            Grade = "EE",
                            MedicineBallPush = 437,
                            OneLegStand = 43,
                            Points = 14u,
                            ShuttleRun = 11310,
                            StandingLongJump = 161,
                            TwelveMinutesRun = 32.5f
                        },
                        new
                        {
                            ID = 42,
                            CoreStrength = 108,
                            Gender = "f",
                            Grade = "EE",
                            MedicineBallPush = 448,
                            OneLegStand = 45,
                            Points = 15u,
                            ShuttleRun = 11170,
                            StandingLongJump = 165,
                            TwelveMinutesRun = 33f
                        },
                        new
                        {
                            ID = 43,
                            CoreStrength = 117,
                            Gender = "f",
                            Grade = "UEE",
                            MedicineBallPush = 459,
                            OneLegStand = 47,
                            Points = 16u,
                            ShuttleRun = 11030,
                            StandingLongJump = 168,
                            TwelveMinutesRun = 34f
                        },
                        new
                        {
                            ID = 44,
                            CoreStrength = 131,
                            Gender = "f",
                            Grade = "UEE",
                            MedicineBallPush = 470,
                            OneLegStand = 49,
                            Points = 17u,
                            ShuttleRun = 10900,
                            StandingLongJump = 172,
                            TwelveMinutesRun = 34.5f
                        },
                        new
                        {
                            ID = 45,
                            CoreStrength = 144,
                            Gender = "f",
                            Grade = "UEE",
                            MedicineBallPush = 481,
                            OneLegStand = 51,
                            Points = 18u,
                            ShuttleRun = 10760,
                            StandingLongJump = 175,
                            TwelveMinutesRun = 35f
                        },
                        new
                        {
                            ID = 46,
                            CoreStrength = 158,
                            Gender = "f",
                            Grade = "UEE",
                            MedicineBallPush = 492,
                            OneLegStand = 54,
                            Points = 19u,
                            ShuttleRun = 10620,
                            StandingLongJump = 179,
                            TwelveMinutesRun = 36f
                        },
                        new
                        {
                            ID = 47,
                            CoreStrength = 171,
                            Gender = "f",
                            Grade = "UEE",
                            MedicineBallPush = 503,
                            OneLegStand = 58,
                            Points = 20u,
                            ShuttleRun = 10480,
                            StandingLongJump = 182,
                            TwelveMinutesRun = 36.5f
                        },
                        new
                        {
                            ID = 48,
                            CoreStrength = 189,
                            Gender = "f",
                            Grade = "UEE",
                            MedicineBallPush = 514,
                            OneLegStand = 64,
                            Points = 21u,
                            ShuttleRun = 10360,
                            StandingLongJump = 186,
                            TwelveMinutesRun = 37f
                        },
                        new
                        {
                            ID = 49,
                            CoreStrength = 207,
                            Gender = "f",
                            Grade = "UED",
                            MedicineBallPush = 525,
                            OneLegStand = 71,
                            Points = 22u,
                            ShuttleRun = 10220,
                            StandingLongJump = 189,
                            TwelveMinutesRun = 38f
                        },
                        new
                        {
                            ID = 50,
                            CoreStrength = 225,
                            Gender = "f",
                            Grade = "UED",
                            MedicineBallPush = 536,
                            OneLegStand = 79,
                            Points = 23u,
                            ShuttleRun = 10080,
                            StandingLongJump = 193,
                            TwelveMinutesRun = 38.5f
                        },
                        new
                        {
                            ID = 51,
                            CoreStrength = 243,
                            Gender = "f",
                            Grade = "UED",
                            MedicineBallPush = 547,
                            OneLegStand = 88,
                            Points = 24u,
                            ShuttleRun = 9940,
                            StandingLongJump = 196,
                            TwelveMinutesRun = 39f
                        },
                        new
                        {
                            ID = 52,
                            CoreStrength = 261,
                            Gender = "f",
                            Grade = "UED",
                            MedicineBallPush = 558,
                            OneLegStand = 100,
                            Points = 25u,
                            ShuttleRun = 9800,
                            StandingLongJump = 200,
                            TwelveMinutesRun = 40f
                        });
                });

            modelBuilder.Entity("FitnessCheck.Data.Entities.CoreStrengthAttempt", b =>
                {
                    b.HasOne("FitnessCheck.Data.Entities.Cohort", "Cohort")
                        .WithMany()
                        .HasForeignKey("CohortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cohort");
                });

            modelBuilder.Entity("FitnessCheck.Data.Entities.MedicineBallPushAttempt", b =>
                {
                    b.HasOne("FitnessCheck.Data.Entities.Cohort", "Cohort")
                        .WithMany()
                        .HasForeignKey("CohortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cohort");
                });

            modelBuilder.Entity("FitnessCheck.Data.Entities.OneLegStandAttempt", b =>
                {
                    b.HasOne("FitnessCheck.Data.Entities.Cohort", "Cohort")
                        .WithMany()
                        .HasForeignKey("CohortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cohort");
                });

            modelBuilder.Entity("FitnessCheck.Data.Entities.ShuttleRunAttempt", b =>
                {
                    b.HasOne("FitnessCheck.Data.Entities.Cohort", "Cohort")
                        .WithMany()
                        .HasForeignKey("CohortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cohort");
                });

            modelBuilder.Entity("FitnessCheck.Data.Entities.StandingLongJumpAttempt", b =>
                {
                    b.HasOne("FitnessCheck.Data.Entities.Cohort", "Cohort")
                        .WithMany()
                        .HasForeignKey("CohortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cohort");
                });

            modelBuilder.Entity("FitnessCheck.Data.Entities.TwelveMinutesRunAttempt", b =>
                {
                    b.HasOne("FitnessCheck.Data.Entities.Cohort", "Cohort")
                        .WithMany()
                        .HasForeignKey("CohortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cohort");
                });
#pragma warning restore 612, 618
        }
    }
}
